classdef config_cl
    properties
        EthernetAddress='';
        
        IPAddress='';
        SerialNumber='';
        
        TransceiverName='';
        TransceiverNumber=0;
        
        TransceiverSoftwareVersion=0;
        TransceiverType='';
        
        ChannelID='';
        ChannelNumber=0;
        
        MaxTxPowerTransceiver=0;
        PulseLength=0.001;
        
        AngleOffsetAlongship=0;
        AngleOffsetAthwartship=0;
        
        AngleSensitivityAlongship=0;
        AngleSensitivityAthwartship=0;
        
        BeamType=1;
        
        BeamWidthAlongship=7;
        BeamWidthAthwartship=7;
        
        EquivalentBeamAngle=0;
        
        Frequency=0;
        FrequencyMaximum=0;
        FrequencyMinimum=0;
        
        Gain=1;
        Impedance=1e3;%ohms
        Ztrd=75;%ohms
        MaxTxPowerTransducer=0;
        SaCorrection=0;
        TransducerName=''
        XML_string='';
        Cal_FM=struct.empty();
        
        TransducerAlphaX=0;%roll
        TransducerAlphaY=0;%pitch
        TransducerAlphaZ=0;%yaw
        
        TransducerCustomName='';
        TransducerMounting='';
        
        TransducerOffsetX=0;%along
        TransducerOffsetY=0;%across
        TransducerOffsetZ=0;%depth
        TransducerOrientation='';
        TransducerSerialNumber='';
        
        Version='';
        EsOffset=0;

        NbQuadrants=4;
        
        RXArrayShape = 'flat';
        TXArrayShape = 'flat';
    end
    
    methods
        function config_str=config2str(config_obj)
            fields={'ChannelID',...
                'TransducerName',...
                'NbQuadrants',...
                'TransceiverSoftwareVersion',...
                'SerialNumber',...
                'IPAddress',...
                'Frequency',...
                'FrequencyMinimum',...
                'FrequencyMaximum',...
                'BeamWidthAlongship',...
                'BeamWidthAthwartship',...
                'BeamType',...
                'PulseLength',...
                'Gain',...
                'SaCorrection'...
                'EquivalentBeamAngle',...
                'AngleOffsetAlongship',...
                'AngleOffsetAthwartship',...
                'AngleSensitivityAlongship',...
                'AngleSensitivityAthwartship'};
            
            fields_name={'Channel ID',...
                'Transducer Name',...
                'Number of Quadrants',...
                'Transceiver Software Version',...
                'Transceiver Serial Number',...
                'IP Address',...
                'Frequency',...
                'Min Frequency',...
                'Max Frequency',...
                'BeamWidth Alongship',...
                'BeamWidth Athwartship',...
                'Beam Type',...
                'Pulse Length Table',...
                'Gain Table',...
                'Sa Correction Table',...
                'Equivalent Beam Angle'...
                'Angle Offset Alongship',...
                'Angle Offset Athwartship',...
                'Angle Sensitivity Alongship',...
                'Angle Sensitivity Athwartship'};
            
                  fact=[...
                1,...%'Channel ID',...
                1,...%'Transducer Name',...
                1,...%'Number of Quadrants',...
                1,...%'Transceiver Software Version',...
                1,...%'Transceiver Serial Number',...
                1,...%'IP Address',...
                1e-3,...%'Frequency',...
                1e-3,...%'Min Frequency',...
                1e-3,...%'Max Frequency',...
                1,...%'BeamWidth Alongship',...
                1,...%'BeamWidth Athwartship',...
                1,...%'Beam Type',...
                1e3,...%'Pulse Length Table',...
                1,...%'Gain Table',...
                1,...%'Sa Correction Table',...
                1,...%'Equivalent Beam Angle'...
                1,...%'Angle Offset Alongship',...
                1,...%'Angle Offset Athwartship',...
                1,...%'Angle Sensitivity Alongship',...
                1,...%'Angle Sensitivity Athwartship'
                ];
            
            fields_fmt={'%s',...
                '%s',...
                '%d',...
                '%.2f',...
                '%s',...
                '%f',...
                '%d kHz',...
                '%d kHz',...
                '%d kHz',...
                '%.2f&deg',...
                '%.2f&deg',...
                '%d',...
                '%.3f ms ',...
                '%.2f dB ',...
                '%.2f dB ',...
                '%.2f dB ',...
                '%.2f&deg',...
                '%.2f&deg',...
                '%.2f',...
                '%.2f'};
            
            
            
            config_str ='<html><ul>Configuration:';
            
            for ifi=1:length(fields)
                if isnumeric(config_obj.(fields{ifi}))
                    val=fact(ifi)*config_obj.(fields{ifi});
                else
                    val=config_obj.(fields{ifi});
                end
                if ~isnan(config_obj.(fields{ifi}))
                    config_str = [config_str '<li><i>' fields_name{ifi} ': </i>' sprintf(fields_fmt{ifi},val) '</li>'];
                end
            end
            config_str = [config_str '</ul></html>'];
        end
        function delete(obj)
            
            if ~isdeployed
                c = class(obj);
                disp(['ML object destructor called for class ',c])
            end
        end
   
    
     end
end

