function [fields,scale_fields,fmt_fields,factor_fields,default_values]=init_fields()

angle_fmt='int16';
angle_factor=1/500;

db_diff_fmt='single';
db_diff_factor=1;

fish_fmt='uint16';
fish_factor=1/1000;

mot_comp_fmt='uint16';
mot_comp_factor=1/500;

% db_fmt='uint16';
% db_factor=-1/300;

db_fmt='single';
db_factor=1;

int_fmt='uint8';
int_factor=1;

lin_fmt='single';
lin_factor=1;

% bool_fmt='int8';
% bool_factor=1;

fields={'power','alongangle','acrossangle',...
    'sp','sv',...
    'img_intensity',...
    'powerunmatched','y_real','y_imag','y_real_filtered','y_imag_filtered','spunmatched','svunmatched',...
    'powerdenoised','svdenoised','spdenoised','snr',...
    'singletarget',  'fishdensity', 'motioncompensation',...
    'acrossphi','alongphi' 'khz'};
scale_fields={'lin','angle','angle',...
    'db','db',...
    'db',...
    'lin','lin','lin','lin','lin','db','db',...
    'lin','db','db','db',...
    'db','density','db',...
    'angle','angle','db_diff'};
fmt_fields={lin_fmt angle_fmt angle_fmt...
    db_fmt db_fmt...
    int_fmt ...
    lin_fmt lin_fmt lin_fmt lin_fmt lin_fmt db_fmt db_fmt...   
    lin_fmt db_fmt db_fmt db_fmt...
    db_fmt fish_fmt mot_comp_fmt...
    angle_fmt angle_fmt db_diff_fmt};

factor_fields=[lin_factor angle_factor angle_factor...
    db_factor db_factor...
    int_factor ...
    lin_factor lin_factor lin_factor lin_factor lin_factor db_factor db_factor...
    lin_factor db_factor db_factor -db_factor...
    db_factor fish_factor mot_comp_factor...
    angle_factor angle_factor db_diff_factor];

default_values=[0 0 0 ...
    -999 -999 ...
    0 ...
    0 0 0 0 0 -999 -999 ...
    0 -999 -999 -999 ...
    -999 0 0 ...
    0 0 0];
