function load_documentation_figure(main_figure)
        pos_fig=[0.2 0.1 0.6 0.8];
        doc_fig=new_echo_figure(main_figure,...
            'Units','normalized',...
            'Position',pos_fig,...
            'Name','ESP3 Documentation',...   
            'Resize','on',...
            'Tag','esp3_doc',...
            'visible','off');
jObject = com.mathworks.mlwidgets.html.HTMLBrowserPanel;
[doc_fig_comp.browser,doc_fig_comp.browser_container] = javacomponent(jObject, [], doc_fig);
set(doc_fig_comp.browser_container, 'Units','norm', 'Pos',[0,0,1,1]);
adress=sprintf('%s/html/ESP3_User_Guide.htm',whereisEcho());
doc_fig_comp.browser.setCurrentLocation(adress);
doc_fig.Visible='on';

end