function createsurveyTable(dbconn)
survey_table=dbconn.fetch('select name FROM sqlite_master WHERE type=''table'' AND name=''survey''');

if isempty(survey_table)
    createsurveyTable_str = ['CREATE TABLE survey ' ...
        '(SurveyName VARCHAR DEFAULT NULL,'...
        'Voyage VARCHAR DEFAULT NULL,'...
        'Timezone FLOAT DEFAULT 0,'...
        'PRIMARY KEY(Voyage)'...
        'ON CONFLICT REPLACE)'];
    dbconn.exec(createsurveyTable_str);
else
    isthereatypecolumn=dbconn.fetch('SELECT sql FROM sqlite_master WHERE type=''table'' AND name=''survey''');
    if ~contains(isthereatypecolumn{1},'Timezone')
        dbconn.exec(['ALTER TABLE survey '...
            'ADD Timezone FLOAT DEFAULT 0']);
    end  
end