function clear_lines_temp(ah)

u=findobj(ah,...
    {'Tag','bottom_temp',...
    '-or','Tag','BrushedLine',...
    '-or','Tag','line_temp',...
    '-or','Tag','bt_temp',...
     '-or','Tag','measurement_text',...
    '-or','Tag','measurement',...
    '-or','Tag','reg_temp',...
    '-or','Tag','zoom_box_temp'});
delete(u);

end