
%% Function
function load_bottom_tab(main_figure,algo_tab_panel)

tab_main=uitab(algo_tab_panel,'Title','Bottom');

[h,l] = get_top_panel_height(7.25);
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%Version 1%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
algo_name= 'BottomDetection';

load_algo_panel('main_figure',main_figure,...
        'panel_h',uipanel(tab_main,'Units','Pixels','Position',[0 0 2*l h]),...
        'algo_name',algo_name,...
        'title','Bottom Detection V1',...
        'save_fcn_bool',true);

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

algo_name= 'BottomDetectionV2';
load_algo_panel('main_figure',main_figure,...
        'panel_h',uipanel(tab_main,'Units','Pixels','Position',[2*l 0 2*l h]),...
        'algo_name',algo_name,...
        'title','Bottom Detection V2',...
        'save_fcn_bool',true);

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

algo_name= 'BottomFeatures';

load_algo_panel('main_figure',main_figure,...
        'panel_h',uipanel(tab_main,'Units','Pixels','Position',[4*l 0 2*l h]),...
        'algo_name',algo_name,...
        'title','Bottom Features Calculation',...
        'save_fcn_bool',false);
    
    
end
