function layer_out=concatenate_layers(layer_1,layer_2)

newname=[layer_1.Filename layer_2.Filename];

if ~isempty(layer_1.Lines)||~isempty(layer_2.Lines)
    line_temp=concatenate_lines([layer_1.Lines layer_2.Lines],'ID');
    lines_temp_2=concatenate_lines(line_temp,'Tag');
else
    lines_temp_2=[];
end
[avail_cids,i1_av,~]=intersect(layer_1.AvailableChannelIDs,layer_2.AvailableChannelIDs,'stable');
[cids,i1,i2]=intersect(layer_1.ChannelID,layer_2.ChannelID,'stable');
layer_out=layer_cl(...
    'AvailableFrequencies',layer_1.AvailableFrequencies(i1_av),...
    'AvailableChannelIDs',avail_cids,...
    'Filename',newname,...
    'Filetype',layer_1.Filetype,...
    'Lines',lines_temp_2,...
    'Transceivers',concatenate_Transceivers(layer_1.Transceivers(i1),layer_2.Transceivers(i2),layer_1.EnvData,layer_2.EnvData),...
    'AttitudeNav',concatenate_AttitudeNavPing(layer_1.AttitudeNav,layer_2.AttitudeNav),...
    'GPSData',concatenate_GPSData(layer_1.GPSData,layer_2.GPSData),...
    'Frequencies',layer_1.Frequencies(i1),...
    'ChannelID',cids,...
    'EnvData',copy(layer_1.EnvData),...
    'Curves',[layer_1.Curves layer_2.Curves]);

layer_out.set_survey_data([layer_1.SurveyData layer_2.SurveyData]);

end